apiVersion: apps/v1
kind: Deployment
metadata:
  name: tnphau-spring-deployment
spec:
  selector:
    matchLabels:
      app: tnphau-spring
  replicas: 3
  template:
    metadata:
      labels:
        app: tnphau-spring
    spec:
      containers:
        - name: tnphau-spring
          image: tnphau/springboot
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6789


---
apiVersion: v1
kind: Service
metadata:
  name: tnphau-spring-service
spec:
  selector:
    app: tnphau-spring
  ports:
    - protocol: "TCP"
      port: 6789
      targetPort: 6789
  type: LoadBalancer